### Spring properties
# Service registers under this name
spring:
  application:
    name: accounts-microservice
    
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-add-partitions: true
      bindings:
        input:
          destination: status
          contentType: application/json
        output:
          destination: status
          contentType: application/json
  
# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 2222

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false